APP_NAME = "ระบบขอที่จอดรถ ป.ป.ช."

REQUEST_STATUSES = ["draft", "pending", "active", "done", "cancelled"]
REQUEST_DATE_STATUSES = ["pending", "active", "done", "cancelled"]
VEHICLE_STATUSES = ["active", "cancelled"]
GUARD_TASK_STATUSES = ["pending", "in_progress", "submitted", "done", "cancelled"]
ATTACHMENT_STATUSES = ["active", "deleted", "replaced"]

REQUEST_STATUS_LABELS = {
    "draft": "ร่าง",
    "pending": "รอดำเนินการ",
    "active": "ใช้งานอยู่",
    "done": "เสร็จสิ้น",
    "cancelled": "ยกเลิก",
}

GUARD_TASK_STATUS_LABELS = {
    "pending": "ยังไม่ได้ทำ",
    "in_progress": "กำลังดำเนินการ",
    "submitted": "ส่งงานแล้ว",
    "done": "เสร็จสิ้น",
    "cancelled": "ยกเลิก",
}

NACC_DEPARTMENTS = [
    "สำนักกิจการคณะกรรมการ ป.ป.ช.",
    "สำนักการประชุม",
    "สำนักบริหารงานกลาง",
    "สำนักตรวจสอบภายใน",
    "สำนักตรวจราชการ",
    "สำนักสืบสวนและกิจการพิเศษ",
    "สำนักไต่สวนคดีพิเศษ",
    "กลุ่มที่ปรึกษาสำนักงาน ป.ป.ช.",
    "สำนักพัฒนาวิชาการด้านการศึกษาและกระบวนการมีส่วนร่วมต้านทุจริต",
    "สำนักประเมินคุณธรรม ความโปร่งใส และส่งเสริมธรรมาภิบาล",
    "สำนักมาตรการป้องกันการทุจริต",
    "สำนักป้องกันการขัดกันแห่งผลประโยชน์และกำกับจริยธรรมภาครัฐ",
    "สำนักพัฒนาระบบตรวจสอบทรัพย์สิน",
    "สำนักตรวจสอบทรัพย์สินภาคการเมือง",
    "สำนักตรวจสอบทรัพย์สินภาครัฐและรัฐวิสาหกิจ ๑",
    "สำนักตรวจสอบทรัพย์สินภาครัฐและรัฐวิสาหกิจ ๒",
    "สำนักตรวจสอบทรัพย์สินภาครัฐและรัฐวิสาหกิจ ๓",
    "สำนักตรวจสอบทรัพย์สินภาครัฐและรัฐวิสาหกิจ ๔",
    "สำนักตรวจสอบทรัพย์สินภาครัฐและรัฐวิสาหกิจ ๕",
    "สำนักตรวจสอบทรัพย์สินภาครัฐและรัฐวิสาหกิจ ๖",
    "สำนักไต่สวนการทุจริตคดีการเมืองการปกครอง ๑",
    "สำนักไต่สวนการทุจริตคดีการเมืองการปกครอง ๒",
    "สำนักไต่สวนการทุจริตคดีการเมืองการปกครอง ๓",
    "สำนักไต่สวนการทุจริตคดีเศรษฐกิจ ๑",
    "สำนักไต่สวนการทุจริตคดีเศรษฐกิจ ๒",
    "สำนักไต่สวนการทุจริตคดีเศรษฐกิจ ๓",
    "สำนักไต่สวนการทุจริตคดีของหน่วยงานที่ขึ้นตรงต่อนายกรัฐมนตรี",
    "สำนักไต่สวนการทุจริตคดีความมั่นคงของรัฐ",
    "สำนักไต่สวนการทุจริตคดีความมั่นคงด้านทรัพยากรธรรมชาติและสิ่งแวดล้อม",
    "สำนักกฎหมาย",
    "สำนักพัฒนาระบบกฎหมาย",
    "สำนักพันธกรณีและความร่วมมือระหว่างประเทศ",
    "สำนักคดี ๑",
    "สำนักคดี ๒",
    "สำนักคดี ๓",
    "สำนักยุทธศาสตร์ด้านการป้องกันและปราบปรามการทุจริต",
    "สำนักวิเคราะห์แผนและงบประมาณ",
    "สำนักบริหารงานคลัง",
    "สำนักบริหารทรัพย์สิน",
    "สำนักสื่อสารองค์กร",
    "สำนักบริหารทรัพยากรบุคคล",
    "สถาบันการป้องกันและปราบปรามการทุจริตแห่งชาติ สัญญา ธรรมศักดิ์",
    "สำนักวิจัยและบริการวิชาการด้านการป้องกันและปราบปรามการทุจริต",
    "สำนักเทคโนโลยีสารสนเทศ",
    "สำนักนวัตกรรม เทคโนโลยี และภูมิสารสนเทศ",
    "อื่นๆ (ระบุเพิ่มเติม)",
]

PARKING_LOCATIONS = [
    "ข้างอาคาร 1 ฝั่งกองสลาก",
    "หน้าอาคาร 3",
    "หน้าอาคาร 2",
    "บริเวณอาคารสถาบันฯ",
    "หน้าอาคาร 4",
    "ชั้นใต้ดินอาคาร 4",
    "อาคาร 4",
    "อาคาร 7",
    "อาคาร 8",
    "อื่นๆ (ระบุเพิ่มเติม)",
]

WORKSHEET_SCHEMAS = {
    "Requests": [
        "request_id",
        "book_no",
        "book_date",
        "received_date",
        "source_agency",
        "car_count",
        "parking_location",
        "note",
        "status",
        "has_vehicle_plates",
        "book_file_url",
        "created_by",
        "created_at",
        "updated_at",
        "cancelled_at",
        "cancelled_by",
        "cancelled_reason",
    ],
    "Request_Dates": [
        "request_date_id",
        "request_id",
        "parking_date",
        "parking_time",
        "month_key",
        "status",
        "created_at",
        "cancelled_at",
        "cancelled_reason",
    ],
    "Vehicles": [
        "vehicle_id",
        "request_id",
        "plate_no",
        "vehicle_note",
        "status",
        "created_at",
        "cancelled_at",
        "cancelled_reason",
    ],
    "Guard_Tasks": [
        "task_id",
        "request_id",
        "request_date_id",
        "parking_date",
        "parking_location",
        "status",
        "assigned_to",
        "submitted_at",
        "completed_at",
        "created_at",
        "updated_at",
    ],
    "Guard_Submissions": [
        "submission_id",
        "task_id",
        "request_id",
        "near_photo_url",
        "far_photo_url",
        "extra_photo_url",
        "note",
        "submitted_by",
        "submitted_at",
        "is_final",
    ],
    "Attachments": [
        "attachment_id",
        "request_id",
        "task_id",
        "file_type",
        "file_name",
        "file_url",
        "mime_type",
        "uploaded_by",
        "uploaded_at",
        "status",
    ],
    "Audit_Log": [
        "log_id",
        "action",
        "target_table",
        "target_id",
        "old_value",
        "new_value",
        "user",
        "created_at",
    ],
}

WORKSHEET_HEADER_LABELS = {
    "Requests": {
        "request_id": "รหัสคำขอ",
        "book_no": "เลขหนังสือ",
        "book_date": "วันที่หนังสือ",
        "received_date": "วันที่รับเรื่อง",
        "source_agency": "สำนัก/หน่วยงาน",
        "car_count": "จำนวนรถ",
        "parking_location": "จุดจอด",
        "note": "หมายเหตุ",
        "status": "สถานะคำขอ",
        "has_vehicle_plates": "มีทะเบียนรถ",
        "book_file_url": "ลิงก์ไฟล์หนังสือ",
        "created_by": "ผู้บันทึก",
        "created_at": "วันที่สร้างข้อมูล",
        "updated_at": "วันที่แก้ไขล่าสุด",
        "cancelled_at": "วันที่ยกเลิก",
        "cancelled_by": "ผู้ยกเลิก",
        "cancelled_reason": "เหตุผลยกเลิก",
    },
    "Request_Dates": {
        "request_date_id": "รหัสวันที่จอด",
        "request_id": "รหัสคำขอ",
        "parking_date": "วันที่จอด",
        "parking_time": "เวลาที่จอด",
        "month_key": "เดือนรายงาน",
        "status": "สถานะวันที่จอด",
        "created_at": "วันที่สร้างข้อมูล",
        "cancelled_at": "วันที่ยกเลิก",
        "cancelled_reason": "เหตุผลยกเลิก",
    },
    "Vehicles": {
        "vehicle_id": "รหัสทะเบียน",
        "request_id": "รหัสคำขอ",
        "plate_no": "เลขทะเบียน",
        "vehicle_note": "หมายเหตุทะเบียน",
        "status": "สถานะทะเบียน",
        "created_at": "วันที่สร้างข้อมูล",
        "cancelled_at": "วันที่ยกเลิก",
        "cancelled_reason": "เหตุผลยกเลิก",
    },
    "Guard_Tasks": {
        "task_id": "รหัสงาน รปภ.",
        "request_id": "รหัสคำขอ",
        "request_date_id": "รหัสวันที่จอด",
        "parking_date": "วันที่ปฏิบัติงาน",
        "parking_location": "จุดจอด",
        "status": "สถานะงาน",
        "assigned_to": "ผู้รับผิดชอบ",
        "submitted_at": "เวลาส่งงาน",
        "completed_at": "เวลาปิดงาน",
        "created_at": "วันที่สร้างงาน",
        "updated_at": "วันที่แก้ไขล่าสุด",
    },
    "Guard_Submissions": {
        "submission_id": "รหัสการส่งงาน",
        "task_id": "รหัสงาน รปภ.",
        "request_id": "รหัสคำขอ",
        "near_photo_url": "รูปใกล้",
        "far_photo_url": "รูปไกล",
        "extra_photo_url": "รูปเสริม",
        "note": "หมายเหตุการส่งงาน",
        "submitted_by": "ผู้ส่งงาน",
        "submitted_at": "เวลาส่งงาน",
        "is_final": "ส่งงานครั้งสุดท้าย",
    },
    "Attachments": {
        "attachment_id": "รหัสไฟล์แนบ",
        "request_id": "รหัสคำขอ",
        "task_id": "รหัสงาน รปภ.",
        "file_type": "ประเภทไฟล์",
        "file_name": "ชื่อไฟล์",
        "file_url": "ลิงก์ไฟล์",
        "mime_type": "MIME type",
        "uploaded_by": "ผู้อัปโหลด",
        "uploaded_at": "เวลาอัปโหลด",
        "status": "สถานะไฟล์",
    },
    "Audit_Log": {
        "log_id": "รหัส log",
        "action": "การกระทำ",
        "target_table": "ตารางเป้าหมาย",
        "target_id": "รหัสเป้าหมาย",
        "old_value": "ค่าเดิม",
        "new_value": "ค่าใหม่",
        "user": "ผู้กระทำ",
        "created_at": "เวลาบันทึก log",
    },
}

def thai_headers_for(worksheet: str) -> list[str]:
    """Return Thai headers for a worksheet in WORKSHEET_SCHEMAS order."""
    labels = WORKSHEET_HEADER_LABELS[worksheet]
    return [labels[field_key] for field_key in WORKSHEET_SCHEMAS[worksheet]]


def field_to_thai_map(worksheet: str) -> dict[str, str]:
    """Map internal English field keys to Thai Google Sheet headers."""
    return WORKSHEET_HEADER_LABELS[worksheet].copy()


def thai_to_field_map(worksheet: str) -> dict[str, str]:
    """Map Thai Google Sheet headers back to internal English field keys."""
    return {thai: field_key for field_key, thai in WORKSHEET_HEADER_LABELS[worksheet].items()}

ID_PREFIXES = {
    "Requests": "REQ",
    "Request_Dates": "DATE",
    "Vehicles": "VEH",
    "Guard_Tasks": "TASK",
    "Guard_Submissions": "SUB",
    "Attachments": "ATT",
    "Audit_Log": "LOG",
}
